server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  profiles:
    active: git # 表示从本地获取配置文件
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://gitee.com/cicadasmile/spring-cloud-config.git
          # 搜索目录
          search-paths: /cloudbaseconfig
      label: master
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
