server:
  port: 80
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置nacos地址
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
# 激活sentinel对Feign的支持
feign:
  sentinel:
    enabled: true