server:
  port: 2001
spring:
  application:
    name: seata-order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?serverTimezone=Japan&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_tx_group # 事务群组，要和nacos上的配置保持一致
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      group: SEATA_GROUP
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true