server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于与Binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: admin
                password: admin
      bindings: # 服务整合的处理
        input: # 信道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 消息类型，文本为text/plain
          binder: defaultRabbit # 要绑定的消息服务的具体设置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka